### ISSUE TITLE
Features.zip

### ISSUE THREAD

**Issue by dyhan0920** [Veleslavia/ICMR2017#1]
Thanks in advance for sharing the pre-processed features.

I would like to use the uploaded file -features.zip, but my zip-extractor is not working.

Could you please check the file is broken or not?

**Comment by Veleslavia** [comment]
Hey!
For me, it seems ok, but I know there could be a downloading issue.
Let me think about how best to share this with you.

**Comment by Veleslavia** [comment]
Hi, I'm very sorry for the late answer. 
I prepared feature splits; the zip files are available here https://drive.google.com/drive/folders/11sm4h0YK7A8attLm0bDwLqRPq6jqi28j?usp=sharing
As for the original zip, I didn't have any problem. I wonder if it might be OS-specific.
Anyway, I hope you still want to use those features and, please, let me know if you'll encounter any other issues.
